# Generated by Django 5.1.2 on 2024-11-09 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
    ]
