# Generated by Django 5.1.2 on 2024-11-12 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_customer_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
    ]
